travis:
  secure:
    BINSTAR_TOKEN: mr6E/XWoyPiZAjpFjeMN4zRiheGnUn+fmDh2NjReYTMuX4SUUhFn/5cnkcwJn6bLNC/Gey9oV2vDvAebjuii8yC02k3f9bdiRFu/pd2bi8K5Cfla2S9lx41rcyArIrZYkhpwe4FcwA9KOdE5RqsDPP279URjpfFVIsB1sZnI3zanCzhnIfZ54BZQL5r1+fguTl10ArIa5h4nwlJhUzbBW0qy6xXT42P00tJ41xRLuqDnDPSXl1bWhF6MOVbzjhjujIIGqKS7dKN8UdV1L6Ornd8RSvCcJDYYeJqPhlBjyzWM+rss3m9os7XJ1Qq/E/QGTYNlJXzPDA24OynhSurtE4HZ6S/C7cjqGjRSyMJs1QR0bwJdFARBwLxaNy5ANDDEsHKQ3zHvnLpydZ2BeMCKkEOm9+4/Ktt3e762AL+vqcW96aU/DxaTKU22sGGwJVtryJYo+213lubP8cRikUn5Il7PGgdqm9uM4eBF3aSSLOVkCw/Qa4dPW6O0rV6P3ng0BWC3aZf9Lw1auVrWOrG5MCYBeFjiKK0ZwK/yZzldj4skR9tIeBNRyxgERu23nBLRckFivvC6Ct3Xt8KHEEqxz3E9b8Ft3HDvyFBTBJrldGOVLI4U4dGRqgPvjWKHFeGzEqrd3WIgD36Ln9F/mVxWEQGMTFPweP83U0oSxg2OwMI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
